import type { Metadata } from "next";
import "./../globals.css";
import AdminNavbar from "@/components/layout/AdminNavbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AdminNavbar />
    <div className="mx-auto px-2 sm:px-6 lg:px-8">
      {children}
    </div>
    </>
  );
}
